### ISSUE TITLE
 Error: Missing value for mandatory field 'exchange'

### ISSUE THREAD

**Issue by johannbotha** [mateodelnorte/servicebus-register-handlers#7]
Hey bro, we miss you already 😄 

Noticed this in `register-handler` 1.6. Works fine on 1.5. 

```
 Error: Missing value for mandatory field 'exchange'
        at encodeQueueBind (...trader-svc/node_modules/amqplib/lib/defs.js:1438:29)
        at module.exports.encodeMethod (...trader-svc/node_modules/amqplib/lib/defs.js:3435:12)
        at Connection.C.sendMethod (...trader-svc/node_modules/amqplib/lib/connection.js:528:15)
        at Channel.C.sendImmediately (...trader-svc/node_modules/amqplib/lib/channel.js:64:26)
        at Channel.C.accept (...trader-svc/node_modules/amqplib/lib/channel.js:431:12)
        at Connection.mainAccept [as accept] (...trader-svc/node_modules/amqplib/lib/connection.js:63:33)
        at Socket.go (...trader-svc/node_modules/amqplib/lib/connection.js:476:48)
        at emitNone (events.js:80:13)
        at Socket.emit (events.js:179:7)
        at emitReadable_ (_stream_readable.js:412:10)
        at emitReadable (_stream_readable.js:406:7)
        at readableAddChunk (_stream_readable.js:158:11)
        at Socket.Readable.push (_stream_readable.js:111:10)
        at TCP.onread (net.js:525:20)
```

**Comment by stefankutko** [comment]
should index.js use `bus[queueType][queueName].exchangeName` instead of `bus.exchangeName`?

**Comment by mateodelnorte** [comment]
I think updating to the latest version of servicebus will resolve the
issue. The latest patch change added the property.

**Comment by mateodelnorte** [comment]
Did you guys find upgrading to the latest version of servicebus fixed this issue?

**Comment by johannbotha** [comment]
Yep, all good with `"servicebus-register-handlers": "0.1.6",`
